services:
  runner:
    build:
      context: ./docker/runner
    container_name: code-sandbox-runner
    restart: unless-stopped
    read_only: true
    tty: true
    stdin_open: true
    security_opt:
      - no-new-privileges:true

    volumes:
      - /tmp/jobs:/tmp/jobs:rw

    tmpfs:
      - /tmp/go-build
      - /tmp/go-mod

  redis:
    image: redis:7.2-alpine
    container_name: code-sandbox-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

volumes:
  redis-data:
