x-runner-go: &runner-go
  build:
    context: ./docker/runner
    dockerfile: go.Dockerfile
  restart: unless-stopped
  read_only: true
  tty: true
  stdin_open: true
  security_opt:
    - no-new-privileges:true
  volumes:
    - /tmp/jobs:/tmp/jobs:rw
  labels:
    sandbox.language: go
  tmpfs:
    - /tmp/go-build
    - /tmp/go-mod

x-runner-python: &runner-python
  build:
    context: ./docker/runner
    dockerfile: python.Dockerfile
  restart: unless-stopped
  read_only: true
  tty: true
  stdin_open: true
  security_opt:
    - no-new-privileges:true
  volumes:
    - /tmp/jobs:/tmp/jobs:rw
  labels:
    sandbox.language: python

x-runner-node: &runner-node
  build:
    context: ./docker/runner
    dockerfile: node.Dockerfile
  restart: unless-stopped
  read_only: true
  tty: true
  stdin_open: true
  security_opt:
    - no-new-privileges:true
  volumes:
    - /tmp/jobs:/tmp/jobs:rw
  labels:
    sandbox.language: node

services:
  runner-go-1:
    <<: *runner-go
    container_name: code-sandbox-runner-go-1

  runner-go-2:
    <<: *runner-go
    container_name: code-sandbox-runner-go-2

  runner-python-1:
    <<: *runner-python
    container_name: code-sandbox-runner-python-1

  runner-python-2:
    <<: *runner-python
    container_name: code-sandbox-runner-python-2

  runner-node-1:
    <<: *runner-node
    container_name: code-sandbox-runner-node-1

  runner-node-2:
    <<: *runner-node
    container_name: code-sandbox-runner-node-2

  redis:
    image: redis:7.2-alpine
    container_name: code-sandbox-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

volumes:
  redis-data:
